apiVersion: v1
data:
  auth: YWRtaW46JDJ5JDA1JDl3ZElydjREdTN4RllNSDN3Z1pqTi45dWtuQTBYM0ZsL2Zma0tNYVdsN1UyN3FxbGU4d3UuCg==
#senha: admin poihj#2341423333333p
kind: Secret
metadata:
  name: auth-prometheus
  namespace: monitoring
type: Opaque

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-ingress-cert
  namespace: monitoring
spec:
  dnsNames:
    - prometheus.<DNS>
  secretName: prometheus-ingress-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: monitoring/auth-prometheus
    nginx.ingress.kubernetes.io/auth-type: basic
  name: prometheus-ingress
  namespace: monitoring
spec:
  tls:
  - hosts:
    - prometheus.<DNS>
    secretName: prometheus-ingress-cert-tls
  rules:
  - host: prometheus.<DNS>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port: 
              number: 9090
