# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Nome amigavel do cliente:'
        # Default value if no value is explicitly provided
        default: 'plsscloud'
        # Input has to be provided for the workflow to run
        required: true
      versaok8s:
        type: choice
        description: Selecione a versão do K8S
        required: true
        default: 1.23.0-4
        options: 
        - 1.23.0-4
        - 1.22.2-4
        - 1.21.1-3
        - 1.20.0-6
        - 1.19.1-8
        - 1.18.3-4
      ocidnodepool:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'OCID da Node Pool Autoscaler:(opcional)'
        # Default value if no value is explicitly provided
        default: ''

      shape_minimo:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Shape minimo do loadbalancer(OKE):'
        # Default value if no value is explicitly provided
        default: '10'
        # Input has to be provided for the workflow to run
        required: true
      shape_maximo:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Shape maximo do loadbalancer(OKE):'
        # Default value if no value is explicitly provided
        default: '100'
        # Input has to be provided for the workflow to run
        required: true
      namespace:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Informe o namespace inicial:'
        # Default value if no value is explicitly provided
        default: 'default'
        # Input has to be provided for the workflow to run
        required: true
      dns:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Informe o dominio do cliente:'
        # Default value if no value is explicitly provided
        default: 'exemplo.com.br'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Gerando-Arquivos:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download do cert manager latest
      run: wget https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml -O 1_cert-manager.yaml
    - name: Gerando yaml do ingress controler
      run: |
        sed -i "s/<SHAPE_MIN>/${{ github.event.inputs.shape_minimo }}/g" 2_ingress_controler_OKE.yaml
        sed -i "s/<SHAPE_MAX>/${{ github.event.inputs.shape_maximo }}/g" 2_ingress_controler_OKE.yaml

    - name: Gerando yaml da dashboard
      run: |
        sed -i "s/<DNS>/${{ github.event.inputs.dns }}/g" 4_dashboard.yaml
    - name: Gerando yaml exemplo
      run: |
        sed -i "s/<DNS>/${{ github.event.inputs.dns }}/g" 5_deployment_exemplo.yaml
        sed -i "s/<NAMESPACE_PADRAO>/${{ github.event.inputs.namespace }}/g" 5_deployment_exemplo.yaml
    - name: Download do metrics server latest
      run: wget https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml -O 6_metrics_server.yaml
    - name: Gerando yaml autoscaler
      run: |
        sed -i "s/<NODEPOOL>/${{ github.event.inputs.ocidnodepool }}/g" 7_cluster_autoscaler_OKE.yaml
        sed -i "s/<K8s-VERSAO>/${{ github.event.inputs.versaok8s }}/g" 7_cluster_autoscaler_OKE.yaml
    - name: Criando pacote zip
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: '${{ github.event.inputs.name }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload do Release
      uses: ncipollo/release-action@v1
      id: release_push
      with:
        artifacts: "${{ github.event.inputs.name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag:  ${{ github.run_id }}
        name: "Arquivos de deploy"
        body: "Arquivos do cliente ${{ github.event.inputs.name }} gerados"
    - name: Link do Release
      run: |
        echo ""
        echo "${{ steps.release_push.outputs.html_url }}"
