# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Nome amigavel do cliente:'
        # Default value if no value is explicitly provided
        default: 'plsscloud'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Gerando-Arquivos:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Download do cert manager latest
      run: wget https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml -O 1_cert-manager.yaml
    - name: Criando pacote zip
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: '${{ github.event.inputs.name }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload do Release
      uses: ncipollo/release-action@v1
      id: release_push
      with:
        artifacts: "${{ github.event.inputs.name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag:  ${{ github.run_id }}
        name: "Arquivos de deploy"
        body: "Arquivos do cliente ${{ github.event.inputs.name }} gerados"
    - name: Link do Release
      run: |
        echo ""
        echo "${{ steps.release_push.outputs.html_url }}"
